name: Deploy to Raspberry Pi 5 without Docker

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update installed .NET workloads
        run: |
          dotnet workload update

      - name: Install the .NET Aspire workload
        run: |
          dotnet workload install aspire

      - name: Restore dependencies
        run: |
          dotnet restore

      - name: Run .NET Aspire AppHost
        run: |
          dotnet run --project AppHost/Republic.AppHost.csproj
